-- Reference only — this table already exists in the Supabase project
-- (created before /api/orders was wired up) and does NOT need to be
-- re-run. Documented here so the column names in pages/api/orders.js
-- make sense without opening the Supabase dashboard.

-- create table orders (
--   id uuid primary key default gen_random_uuid(),
--   created_at timestamptz not null default now(),
--   status text,
--   nom text,
--   telephone text,
--   entreprise text,
--   email text,
--   wilaya text,
--   adresse text,
--   technique text,
--   logo_filename text,
--   notes text,
--   line_items jsonb,
--   pay_mode text,
--   subtotal integer,
--   volume_discount_rate numeric,
--   volume_discount_amount integer,
--   payment_discount_amount integer,
--   total_qty integer,
--   total integer
-- );
