// Parses the structured order message generated by the /commande wizard
// (see the `msg` template in pages/commande.js) back into fields. Customers
// receive that text pre-filled in WhatsApp and send it as-is, so an inbound
// webhook message matching this shape is almost always a real order — any
// other inbound text (a question, a reply) just doesn't match and is stored
// as a plain message instead.

const FIELD_PATTERNS = {
  nom: /👤 \*Nom :\* (.+)/,
  entreprise: /🏢 \*Entreprise :\* (.+)/,
  tel: /📞 \*Tél :\* (.+)/,
  email: /📧 \*Email :\* (.+)/,
  wilaya: /📍 \*Wilaya :\* (.+)/,
  adresse: /🏠 \*Adresse :\* (.+)/,
  technique: /🔧 \*Technique :\* (.+)/,
  logo: /📎 \*Logo :\* (.+)/,
  paiement: /💳 \*Paiement :\* (.+)/,
  quantiteTotale: /📦 \*Quantité totale :\* (\d+) pièces/,
  sousTotal: /💰 \*Sous-total :\* ([\d\s., ]+) DA/,
  total: /✅ \*TOTAL : ([\d\s., ]+) DA\*/,
}

// e.g. "👕 *Polo* (Blanc) — 50 pcs × 1 200 DA → S:10 | M:20 | L:20"
const PRODUCT_LINE = /^\S+ \*(.+)\* \((.+)\) — (\d+) pcs × ([\d\s., ]+) DA(?: → (.+))?$/

const toNumber = (s) => Number(String(s).replace(/[\s., ]/g, ''))

export function parseOrderMessage(text) {
  if (!text || !text.includes('COMMANDE — DJIMMY PRINTS')) {
    return { isOrder: false }
  }

  const lines = text.split('\n')
  const fields = {}
  for (const [key, pattern] of Object.entries(FIELD_PATTERNS)) {
    for (const line of lines) {
      const m = line.match(pattern)
      if (m) { fields[key] = m[1].trim(); break }
    }
  }

  const products = []
  let inProducts = false
  for (const line of lines) {
    if (line.includes('*PRODUITS :*')) { inProducts = true; continue }
    if (!inProducts) continue
    const m = line.match(PRODUCT_LINE)
    if (m) {
      products.push({
        name: m[1].trim(),
        color: m[2].trim(),
        qty: Number(m[3]),
        unitPrice: toNumber(m[4]),
        sizes: m[5] ? m[5].trim() : null,
      })
    } else if (line.startsWith('━') || line.trim() === '') {
      inProducts = false
    }
  }

  const notesMatch = text.match(/💬 \*Notes :\*\n([\s\S]+?)\n━/)

  return {
    isOrder: true,
    nom: fields.nom || null,
    entreprise: fields.entreprise || null,
    tel: fields.tel || null,
    email: fields.email || null,
    wilaya: fields.wilaya || null,
    adresse: fields.adresse || null,
    technique: fields.technique || null,
    logo: fields.logo || null,
    paiement: fields.paiement || null,
    quantiteTotale: fields.quantiteTotale ? Number(fields.quantiteTotale) : null,
    sousTotal: fields.sousTotal ? toNumber(fields.sousTotal) : null,
    total: fields.total ? toNumber(fields.total) : null,
    notes: notesMatch ? notesMatch[1].trim() : null,
    products,
  }
}
